### ISSUE TITLE
result column order is not respected

### ISSUE THREAD

**Issue by Chaz6** [alash3al/sqler#15]
In my sqler.hcl is the stanza
```
logins {
    methods = ["GET"]
    exec = "SELECT id,user,pass,source,time FROM logins ORDER BY id DESC LIMIT 50;"
}
```
however the resulting json has the columns in alphabetical order:-
```
id, pass, source, time, user
```

**Comment by alash3al** [comment]
because the column ordering isn't important, it will return an object for each row, so where is the problem when you know that the id column is `id`, and so?

**Comment by Chaz6** [comment]
When I am viewing the output (either directly or transformed), I want to see the order I specify because it is hard for me when the columns are unordered. Not all tools allow you to re-order columns. I would prefer that the source output them in the order I specify.
