### ISSUE TITLE
sqlite3 is not supported ?

### ISSUE THREAD

**Issue by restagner** [alash3al/sqler#17]
It does not appear that sqlite3 is supported under Linux.  I downloaded the latest vesion (2.0) onto my Linux workstation and attempted to run the following

```text
$ sqler -driver sqlite3 -dsn /home/restagner/sqlite/roberts.db -config /home/restagner/SQLer/config.hcl 
[sqlite3] /home/restagner/sqlite/roberts.db - connection error - (Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub)
```

Am I missing something obvious, here?

**Comment by alash3al** [comment]
It is supported,  but seems it is a compile bug,  anyway,  I'll recompile it on a linux machine,  as well as there will be a docker image.

**Comment by restagner** [comment]
That would be great, @alash3al.  I look forward to the recompiled release!!

**Comment by restagner** [comment]
Sure. I'll download that later tonight and let you know.  This is the release you are referring to, correct?

https://github.com/alash3al/sqler/releases/download/v2.0/sqler_linux_amd64.zip

just want to make sure

**Comment by alash3al** [comment]
yes, that is right, hope it will work as expected

**Comment by alash3al** [comment]
Thanks for your notice, I forgot to update the version number
