### ISSUE TITLE
Support data migrations

### ISSUE THREAD

**Issue by gedw99** [alash3al/sqler#18]
I presume this is needed as a formal method because you need to check what version the db is at.

Normally data migrations check versions so that they know which migration scripts should be run.
There are other approaches too like naming each script with a daytime stamp and internally storing the datetine inside the db so that a user can just through all scripts at the db and it only runs the scripts after its internal datetime stamp.

**Comment by alash3al** [comment]
In my opinion,  sqler should only one thins which is simplifying api creation,  there are many tools for data migrations out there.

**Comment by gedw99** [comment]
@alash3al your right. Will look for a golang based migration tool
