### ISSUE TITLE
Is it possible make config more flexible with input?

### ISSUE THREAD

**Issue by HillLiu** [alash3al/sqler#22]
If I want cols and table pass from input.

And how to pass array to config?

some idea from sigil, maybe useful?
https://github.com/gliderlabs/sigil

```

get {
	bind {
		table = "$input.table"
                 cols = "$input.cols"
	}

	methods = ["GET"]

	exec = <<SQL
		SELECT :cols FROM :table;
	SQL
}

```

**Comment by alash3al** [comment]
Sorry for the late response, but this is may be a security issue,  as some may pass a malformed input that break your query. 

So I think that I shouldn't do it.

**Comment by HillLiu** [comment]
Got it, I'll keep trace this project to see it become more powerful and fit to use.

**Comment by alash3al** [comment]
Thank you @HillLiu ,

The project will be more powerful with the contributions from all, event if the contribution is just a question, issue ... etc
