### ISSUE TITLE
QUESTION  :  Stored Procedures and Scalability

### ISSUE THREAD

**Issue by aniruddhha** [alash3al/sqler#31]
At first,  I would like to say thanks for all your efforts :tada: :tada: :tada: :tada:. You have built a fantastic product. 

I would like to ask 2 questions

1. I want to use it just for calling stored procedures, How do I call it from MSSQL?
2. I would like to use it for huge systems like full-fledged ERP (db would be MSSQL only), so do I need to worry about scalability? 
  
Thanks again for your all efforts and support.

**Comment by BusbyActual** [comment]
@aniruddhha Did you find any answer? I'd like to use this library purely for calling stored procedures as well.

**Comment by alash3al** [comment]
sorry for that late reply, really sorry,

- regarding stored procedures:
> there is no issue, sqler executes pure sql queries, so anything within the sql context will work fine

- regarding scalability, as you see, sqler is a portable software, you can distribute it easily  behind a load balancer
