### ISSUE TITLE
Best practise for having sqler always running on the server

### ISSUE THREAD

**Issue by nikolai-belkin** [alash3al/sqler#34]
Hi, just wondering what's the best practise for always running the sql on a windows server.

I can setup a batch file to run the sql with the connections & config files and set a windows task to execute it on windows login, but wondering if there is a better way of doing this?

Thanks

**Comment by alash3al** [comment]
I'm not a windows user but in my opinion, something like:

- install the batch file you wrote as a service in windows
- using [pm2](https://pm2.keymetrics.io/)

Again: "I'm not a windows user so I don't know more info"

if you found a better solution just ping me, also feel free to contribute to the base code or even the readme to help any other windows user.
